[package]
name = "eix"
version = "0.1.0"
edition = "2024"
description = "Library for handling the EIX-file format of Gentoo Linux"
license = "MIT"
readme = "README.md"
repository = "https://github.com/Komplix/eix-lib"
[dependencies]

